# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "egg"

# URL
baseurl:            ""
permalink:          /:year/:month/:day/:title.html

google_analytics: UA-8848238-2

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "/about"
  - name:           "Repositories"
    href:           "/repositories"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-github-metadata
